[project]
name = "my-course-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "langchain>=1.0.2",
    "langchain-google-genai>=3.0.0",
    "langgraph>=1.0.5",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "langchain-openai>=1.0.2",
    "langgraph-cli[inmem]>=0.4.11",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
